#!/usr/bin/env python3
"""Assemble a script.json into Remotion timeline props and render with the engine.

A project directory looks like:
    <project>/
      script.json          shots[], music mood, brand (generated by `pdd new`)
      assets/              clips referenced by shot.src / srcL / srcR (relative names)
      audio/               s<n>.mp3 + manifest.json   (from vo.py)        [optional]
      music.mp3            background bed              (from music.py)     [optional]

    python tools/build.py --project projects/my-demo
    python tools/build.py --project projects/my-demo --dry   # write props.json, skip render

Each shot maps to a Timeline Segment. When a shot has a `vo` line, the on-screen
caption defaults to that exact line (subtitles match the narration) and the shot's
duration is stretched to fit the spoken audio.
"""
import argparse, hashlib, json, math, os, re, shutil, subprocess, sys, tempfile

from contracts import (
    media_duration,
    resolve_source_manifests,
    sha256_file,
    summarize,
    validate_script,
)

HERE = os.path.dirname(os.path.abspath(__file__))

# words that read as AI/marketing filler — linted out of VO + captions in yc mode
BUZZWORDS = ["revolutioniz", "seamless", "AI-powered", "game-chang", "cutting-edge",
             "empower", "unleash", "supercharge", "effortless", "next-generation"]
STATIC_DEAD_AIR_SEC = 4.5


def compile_frame_plan(segs, fps):
    """Normalize segment durations to one canonical integer-frame plan."""
    cursor = 0
    rows = []
    for seg in segs:
        frames = max(1, round(float(seg["durSec"]) * fps))
        seg["durFrames"] = frames
        seg["durSec"] = frames / fps
        rows.append({"n": seg.get("n"), "kind": seg["kind"],
                     "startFrame": cursor, "endFrame": cursor + frames,
                     "frames": frames, "startSec": cursor / fps,
                     "endSec": (cursor + frames) / fps})
        cursor += frames
    return rows, cursor


def load_json(path):
    with open(path) as fh:
        return json.load(fh)


def write_json(path, value):
    """Atomically publish machine-readable build state."""
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=f".{os.path.basename(path)}.",
                               dir=os.path.dirname(os.path.abspath(path)))
    try:
        with os.fdopen(fd, "w") as fh:
            json.dump(value, fh, indent=2)
            fh.write("\n")
        os.replace(tmp, path)
    finally:
        if os.path.exists(tmp):
            os.unlink(tmp)


def compute_build_id(records, config):
    """Hash every render-affecting input plus explicit build configuration."""
    canonical = {
        "config": config,
        "inputs": sorted(
            ({"kind": r["kind"], "name": r["name"], "sha256": r["sha256"]}
             for r in records),
            key=lambda r: (r["kind"], r["name"]),
        ),
    }
    blob = json.dumps(canonical, sort_keys=True, separators=(",", ":")).encode()
    return hashlib.sha256(blob).hexdigest()[:16]


def bind_capture_source_inputs(script, project, bind_input):
    """Bind repo-native capture sources through the same artifact input recorder."""
    sources, findings = resolve_source_manifests(script, project)
    if findings:
        messages = "; ".join(f"{item.code}: {item.message}" for item in findings)
        raise ValueError(messages)
    return [
        bind_input("capture-source", name, path)
        for name, path in sources
    ]


def bind_claim_evidence_inputs(script, project, bind_input):
    """Bind local claim evidence while leaving external URLs validation-only.

    Claim evidence follows the same trust boundary as repo-native capture sources:
    local references must be project-relative files, and neither their lexical path
    nor a resolved symlink may escape the project. Multiple claims may cite the same
    file; bind that file once so the artifact manifest stays canonical.
    """
    project_abs = os.path.abspath(project)
    project_real = os.path.realpath(project_abs)
    resolved = []
    seen_real_paths = set()

    for claim_index, claim in enumerate(script.get("claims") or []):
        if not isinstance(claim, dict):
            continue
        evidence = claim.get("evidence")
        values = evidence if isinstance(evidence, list) else [evidence]
        for evidence_index, value in enumerate(values):
            if not value:
                continue
            name = str(value)
            if re.match(r"^[a-z]+://", name, re.I):
                continue
            field = f"claims[{claim_index}].evidence"
            if isinstance(evidence, list):
                field += f"[{evidence_index}]"
            if os.path.isabs(name):
                raise ValueError(f"{field} must be project-relative: {name}")

            absolute = os.path.abspath(os.path.join(project_abs, name))
            real = os.path.realpath(absolute)
            try:
                lexical_inside = os.path.commonpath([project_abs, absolute]) == project_abs
                real_inside = os.path.commonpath([project_real, real]) == project_real
            except ValueError:
                lexical_inside = real_inside = False
            if not lexical_inside or not real_inside:
                raise ValueError(f"{field} escapes the project: {name}")
            if not os.path.exists(absolute):
                raise ValueError(f"{field} does not exist: {name}")
            if not os.path.isfile(absolute):
                raise ValueError(f"{field} is not a file: {name}")

            dedupe_key = os.path.normcase(real)
            if dedupe_key in seen_real_paths:
                continue
            seen_real_paths.add(dedupe_key)
            canonical_name = os.path.relpath(absolute, project_abs).replace(os.sep, "/")
            resolved.append(bind_input("claim-evidence", canonical_name, absolute))
    return resolved


def _aligned_narration_ranges(script, shot_n):
    """Return valid global narration ranges explicitly assigned to one shot."""
    entries = script.get("narrationMap")
    if not isinstance(entries, list):
        return []
    ranges = []
    for entry in entries:
        if not isinstance(entry, dict) or entry.get("shotN") != shot_n:
            continue
        try:
            start = float(entry.get("startSec"))
            end = float(entry.get("endSec"))
        except (TypeError, ValueError):
            continue
        if math.isfinite(start) and math.isfinite(end) and start >= 0 and end > start:
            ranges.append((start, end))
    return ranges


def _longest_unnarrated_hold(start, end, ranges):
    """Measure the longest gap left after mapped narration is clipped to a shot."""
    covered = sorted(
        (max(start, cue_start), min(end, cue_end))
        for cue_start, cue_end in ranges
        if cue_end > start and cue_start < end
    )
    merged = []
    for cue_start, cue_end in covered:
        if merged and cue_start <= merged[-1][1]:
            merged[-1] = (merged[-1][0], max(merged[-1][1], cue_end))
        else:
            merged.append((cue_start, cue_end))

    if not merged:
        return end - start, "full-shot"

    gaps = [(merged[0][0] - start, "leading")]
    gaps.extend((right[0] - left[1], "internal") for left, right in zip(merged, merged[1:]))
    gaps.append((end - merged[-1][1], "trailing"))
    # Prefer naming a trailing hold when equal-length gaps tie: it is the most likely to feel
    # like a card was left hanging after the spoken thought finished.
    return max(gaps, key=lambda gap: (gap[0], gap[1] == "trailing"))


def lint(script, segs, music, mode):
    """Pacing + honesty lints. Returns (errors, warnings); yc mode makes the YC contract hard."""
    errors, warns = [], []
    total = sum(s["durSec"] for s in segs)
    cursor = 0.0
    for s in segs:
        start = cursor
        end = start + float(s["durSec"])
        cursor = end
        if s["kind"] in ("clip", "split", "strip"):
            continue
        ranges = _aligned_narration_ranges(script, s.get("n"))
        if ranges:
            hold, position = _longest_unnarrated_hold(start, end, ranges)
            if hold > STATIC_DEAD_AIR_SEC:
                warns.append(
                    f"static {s['kind']} has a {hold:.3g}s {position} unnarrated hold "
                    f"(>{STATIC_DEAD_AIR_SEC}s reads as dead air)"
                )
        elif s["durSec"] > STATIC_DEAD_AIR_SEC:
            # Preserve the legacy duration-only heuristic when this shot has no aligned cue.
            warns.append(
                f"static {s['kind']} held {s['durSec']}s "
                f"(>{STATIC_DEAD_AIR_SEC}s reads as dead air)"
            )
    text = " ".join((sh.get("vo", "") or "") + " " + (sh.get("caption", "") or "") for sh in script["shots"])
    hits = sorted({b for b in BUZZWORDS if re.search(b, text, re.I)})
    if hits:
        (errors if mode == "yc" else warns).append(f"buzzwords in vo/captions: {', '.join(hits)}")
    if mode == "yc":
        if total > 90:
            errors.append(f"runtime {total:.0f}s > 90s hard ceiling for a YC demo (target 60s)")
        elif total > 75:
            warns.append(f"runtime {total:.0f}s > 75s (YC target is ~60s)")
        if segs and segs[0]["kind"] not in ("clip", "split"):
            errors.append(f"first beat is a {segs[0]['kind']} — YC demos open on the product mid-action, never a logo/title card")
        if music:
            warns.append("music bed present — a YC application demo reads better as a plain screen recording (music stays only inside a product-output excerpt); pass --keep-music to override")
        if segs and segs[-1]["kind"] == "cta" and segs[-1]["durSec"] > 2.4:
            warns.append(f"end card held {segs[-1]['durSec']}s (cap ~2s, keep late motion)")
    return errors, warns


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--project", required=True)
    ap.add_argument("--engine", default=os.path.join(HERE, "..", "engine"))
    ap.add_argument("--out", default="")
    ap.add_argument("--fps", type=int, default=0)
    ap.add_argument("--dry", action="store_true")
    ap.add_argument("--mode", choices=["default", "yc"], default="default",
                    help="yc: enforce the YC application-demo contract (60s target, product-first open, no wrapper music, buzzword lint)")
    ap.add_argument("--keep-music", action="store_true", help="yc mode: keep the music bed anyway")
    ap.add_argument("--profile", default="", help="production profile override (yc_3m, investor, sales, yc_60)")
    ap.add_argument("--contracts", choices=["auto", "off", "warn", "strict"], default="auto",
                    help="deterministic production-contract gate; auto blocks errors and enables strong checks when declared")
    args = ap.parse_args()

    proj = os.path.abspath(args.project)
    engine = os.path.abspath(args.engine)
    pub = os.path.join(engine, "public")
    script_path = os.path.join(proj, "script.json")
    script = load_json(script_path)
    fps = args.fps or script.get("fps", 30)

    if args.contracts != "off":
        findings = validate_script(script, proj, args.profile or None)
        report = summarize(findings)
        for finding in findings:
            where = f" shot {finding.shot}" if finding.shot is not None else ""
            print(f"  CONTRACT {finding.severity}: {finding.code}{where} — {finding.message}")
        active = bool(script.get("production") or script.get("editorialContract")
                      or script.get("narration") or script.get("finalNarration") or args.profile)
        block_warnings = args.contracts == "strict"
        block_errors = args.contracts != "warn"
        if (block_errors and report["errors"]) or (block_warnings and report["warnings"]):
            sys.exit(f"production contract failed: {report['errors']} errors, {report['warnings']} warnings")
        if args.contracts == "auto" and active:
            print(f"  CONTRACT PASS: {report['warnings']} warning(s)")

    # Brand: <project>/brand.json is the source of truth (palette/font/logo flow into the engine
    # theme + the CTA wordmark); falls back to the script's inline `brand` block.
    brand_path = os.path.join(proj, "brand.json")
    brand = load_json(brand_path) if os.path.exists(brand_path) else script.get("brand", {})
    raw_theme = brand.get("theme") or script.get("theme") or {}

    vo = {}
    man = os.path.join(proj, "audio", "manifest.json")
    if os.path.exists(man):
        for m in load_json(man):
            vo[m["n"]] = m

    # Bind the render to the exact script + referenced assets. Each build gets an isolated
    # staticFile namespace; projects with the same filenames can no longer contaminate each
    # other through the shared engine/public directory.
    adir = os.path.join(proj, "assets")
    referenced = sorted({str(sh[k]) for sh in script["shots"] for k in ("src", "srcL", "srcR")
                         if sh.get(k)})
    source_records = []
    input_records = []

    def bind_input(kind, name, path, required=True):
        absolute = os.path.abspath(path)
        if not os.path.isfile(absolute):
            if required:
                sys.exit(f"missing {kind} input: {absolute}")
            return None
        record = {"kind": kind, "name": str(name), "path": absolute,
                  "sha256": sha256_file(absolute), "bytes": os.path.getsize(absolute)}
        input_records.append(record)
        return record

    bind_input("script", "script.json", script_path)
    if os.path.exists(brand_path):
        bind_input("brand", "brand.json", brand_path)
    try:
        bind_claim_evidence_inputs(script, proj, bind_input)
    except ValueError as exc:
        sys.exit(f"invalid claim evidence: {exc}")
    try:
        bind_capture_source_inputs(script, proj, bind_input)
    except ValueError as exc:
        sys.exit(f"invalid capture source manifest: {exc}")
    if os.path.exists(man):
        bind_input("vo-manifest", "audio/manifest.json", man)
    for name in referenced:
        src = os.path.abspath(os.path.join(adir, name))
        if os.path.commonpath([adir, src]) != os.path.abspath(adir):
            sys.exit(f"asset path escapes project assets/: {name}")
        record = bind_input("picture", name, src, required=False)
        if record:
            source_records.append({k: record[k] for k in ("name", "path", "sha256", "bytes")})
    for entry in vo.values():
        bind_input("shot-vo", f"audio/{entry['file']}", os.path.join(proj, "audio", entry["file"]))

    narration = script.get("narration") if isinstance(script.get("narration"), dict) else None
    if narration and narration.get("mix", True) and vo:
        sys.exit("master narration and per-shot audio/manifest.json cannot both be active")
    narration_source = None
    if narration and narration.get("mix", True):
        name = narration.get("file")
        narration_source = (name if os.path.isabs(str(name or ""))
                            else os.path.join(proj, str(name or "")))
        bind_input("narration-master", str(name), narration_source)
        timing_name = narration.get("timingFile")
        if timing_name:
            timing_source = (timing_name if os.path.isabs(str(timing_name))
                             else os.path.join(proj, str(timing_name)))
            bind_input("narration-timing", str(timing_name), timing_source)
    music_source = os.path.join(proj, "music.mp3")
    if os.path.exists(music_source):
        bind_input("music", "music.mp3", music_source)
    logo = raw_theme.get("logo") or (brand.get("logo") if isinstance(brand, dict) else None)
    if logo:
        logo_source = logo if os.path.isabs(logo) else os.path.join(proj, "assets", os.path.basename(logo))
        bind_input("brand-logo", str(logo), logo_source)
    for code_path in (os.path.join(engine, "src", "Timeline.tsx"),
                      os.path.join(engine, "src", "Root.tsx"),
                      os.path.join(engine, "package-lock.json")):
        bind_input("engine", os.path.relpath(code_path, engine), code_path)
    sfxdir = os.path.join(pub, "sfx")
    for accent in sorted({str(sh["accent"]) for sh in script["shots"] if sh.get("accent")}):
        bind_input("sfx", f"sfx/{accent}.mp3", os.path.join(sfxdir, f"{accent}.mp3"))

    production_hint = script.get("production") if isinstance(script.get("production"), dict) else {}
    build_config = {"fps": fps, "profile": args.profile or production_hint.get("profile"),
                    "mode": args.mode, "keepMusic": bool(args.keep_music)}
    build_id = compute_build_id(input_records, build_config)
    # Remotion receives a build-scoped public directory. It no longer copies the shared
    # engine/public tree (which may contain hundreds of megabytes of stale or unrelated footage).
    stage_root = os.path.join(proj, "out", "builds", build_id, "public")
    stage_assets = os.path.join(stage_root, "assets")
    stage_audio = os.path.join(stage_root, "audio")
    os.makedirs(stage_assets, exist_ok=True)
    os.makedirs(stage_audio, exist_ok=True)
    for record in source_records:
        dst = os.path.join(stage_assets, record["name"])
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copy(record["path"], dst)
    for entry in vo.values():
        name = entry["file"]
        src = os.path.join(proj, "audio", name)
        if os.path.exists(src):
            dst = os.path.join(stage_audio, name)
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            shutil.copy(src, dst)
    referenced_accents = sorted({str(sh["accent"]) for sh in script["shots"] if sh.get("accent")})
    if referenced_accents:
        os.makedirs(os.path.join(stage_root, "sfx"), exist_ok=True)
        for accent in referenced_accents:
            shutil.copy(os.path.join(sfxdir, f"{accent}.mp3"),
                        os.path.join(stage_root, "sfx", f"{accent}.mp3"))

    narration_props = None
    if narration and narration.get("mix", True):
        ext = os.path.splitext(narration_source)[1] or ".wav"
        staged_name = f"master{ext.lower()}"
        shutil.copy(narration_source, os.path.join(stage_audio, staged_name))
        probed_narration_sec = media_duration(narration_source)
        narration_props = {
            "src": f"audio/{staged_name}",
            "startAtSec": float(narration.get("startsAtSec", 0.0)),
            "durationSec": float(probed_narration_sec
                                 if probed_narration_sec is not None
                                 else narration.get("expectedDurationSec", 0.0)),
            "volume": float(narration.get("volume", 1.0)),
        }
    music = None
    if os.path.exists(music_source):
        stage_music = os.path.join(stage_root, "music")
        os.makedirs(stage_music, exist_ok=True)
        shutil.copy(music_source, os.path.join(stage_music, "bed.mp3"))
        music = "music/bed.mp3"
    sfx = {accent: f"sfx/{accent}.mp3" for accent in referenced_accents}

    def asset(p):
        return f"assets/{p}" if p else p

    def build_theme():
        """Map brand.json (theme/palette/colors + friendly aliases) -> the engine Theme token shape.
        Only keys that resolve to a value are emitted; the engine fills the rest from DEFAULT_THEME,
        so an empty result (e.g. the promo, which has no palette) renders byte-identically."""
        palette = brand.get("palette", {}) if isinstance(brand, dict) else {}
        colors = brand.get("colors", {}) if isinstance(brand, dict) else {}

        # NB: only read COLOR tokens from theme/palette/colors — never from top-level brand keys,
        # which hold CTA wordmark text (brand.accent is "Director", not a color).
        def pick(*keys):
            for k in keys:
                v = raw_theme.get(k) or palette.get(k) or colors.get(k)
                if v:
                    return v
            return None

        amap = {
            "bg": ("bg", "background"), "ink": ("ink", "text", "foreground"),
            "sub": ("sub", "muted"), "accent": ("accent", "green", "primary", "brandColor"),
            "accentDeep": ("accentDeep", "greenDeep", "primaryDeep"),
            "warn": ("warn", "warning"), "line": ("line", "border"),
            "onAccent": ("onAccent",),
            "grad": ("grad",), "gradFilm": ("gradFilm",), "scrim": ("scrim",), "scrimDim": ("scrimDim",),
        }
        out = {}
        for ek, aliases in amap.items():
            v = pick(*aliases)
            if v:
                out[ek] = v
        # font may also be a top-level brand key (font/fontFamily); colors never are
        font = pick("font", "fontFamily") or (brand.get("font") or brand.get("fontFamily") if isinstance(brand, dict) else None)
        if font:
            # a bare family name renders as browser-default serif when the font isn't installed
            # on the render machine — always carry the bundled fallback stack behind it
            if "," not in font:
                font = f'{font}, Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif'
            out["font"] = font
        logo = raw_theme.get("logo") or (brand.get("logo") if isinstance(brand, dict) else None)
        if logo:
            lp = logo if os.path.isabs(logo) else os.path.join(proj, "assets", os.path.basename(logo))
            if os.path.exists(lp):
                shutil.copy(lp, os.path.join(stage_assets, os.path.basename(lp)))
                out["logo"] = f"assets/{os.path.basename(lp)}"
        return out

    theme = build_theme()

    locked_sources = set()
    production = script.get("production") if isinstance(script.get("production"), dict) else {}
    for lock in production.get("sourceLocks", []) or []:
        if isinstance(lock, str):
            locked_sources.add(lock)
        elif isinstance(lock, dict) and lock.get("src") and lock.get("preserveFraming", True):
            locked_sources.add(lock["src"])

    segs = []
    for sh in script["shots"]:
        n = sh["n"]
        kind = sh.get("kind", "clip")
        vo_text = (sh.get("vo") or "").strip()
        # subtitles default to the spoken line; a shot may override (incl. "" or false to suppress
        # the lower-third). The engine auto-chunks the text into one-row pieces.
        cap = sh["caption"] if "caption" in sh else vo_text
        if cap is False or cap is None:
            cap = ""
        durSec = float(sh.get("durSec", 2.5))
        vo_file = None
        if n in vo:
            vo_file = f"audio/{vo[n]['file']}"
            durSec = max(durSec, vo[n]["seconds"] + 0.2)
            # kill dead air: a narrated CARD holds exactly VO + a short tail (clips may breathe longer,
            # they carry footage). Opt out per shot with "hold": true.
            if kind not in ("clip", "split", "strip") and not sh.get("hold"):
                durSec = min(durSec, vo[n]["seconds"] + float(sh.get("holdTail", 0.7)))
        seg = {
            "n": n, "kind": kind, "durSec": round(durSec, 6),
            "caption": cap if kind in ("clip", "split", "strip") else "",
            "captionStyle": sh.get("captionStyle", "label"),
            "chapter": sh.get("chapter", ""),
        }
        for k in ("storyBeat", "storyBeats", "continuityId", "stateId", "transitionReason", "sourceType",
                  "liveState", "actor", "actionRisk", "claimIds", "preserveFraming",
                  "editorialIntent"):
            if k in sh:
                seg[k] = sh[k]
        preserve_framing = bool(sh.get("preserveFraming") or sh.get("src") in locked_sources)
        if preserve_framing:
            seg["preserveFraming"] = True
        if vo_file:
            seg["vo"] = vo_file
            seg["voSec"] = vo[n]["seconds"]   # caption chunks spread across the actual spoken window
        if sh.get("showChapter"):            # chapter pills are opt-in now (default: never rendered)
            seg["showChapter"] = True
        if sh.get("flash"):
            seg["flash"] = True
        if sh.get("transition") in ("cut", "xfade"):
            seg["transition"] = sh["transition"]
        if sh.get("accent"):                 # per-beat sound (sfx key, e.g. "success_chime")
            seg["accent"] = sh["accent"]
        if "accentAtSec" in sh:              # optional: land the sfx on the actual UI event, not segment start
            seg["accentAtSec"] = sh["accentAtSec"]
        for k in ("captionTop", "captionBottom"):
            if k in sh:
                seg[k] = sh[k]
        if kind == "clip":
            seg.update(src=asset(sh["src"]), inSec=sh.get("inSec", 0), scale=sh.get("scale", 1.0))
            for k in ("startScale", "endScale", "focusX", "focusY", "panX", "panY", "objectFit", "vignette"):
                if k in sh:
                    seg[k] = sh[k]
            if preserve_framing:
                seg["objectFit"] = "contain"
            # zoom REGIONS (Screen-Studio style). Explicit `zooms` wins; else a legacy
            # clickX/clickY/clickAtSec shot derives one region around the click.
            zooms = sh.get("zooms")
            if not zooms and sh.get("clickAtSec") is not None:
                zooms = [{
                    "atSec": max(0.0, float(sh["clickAtSec"]) - 0.9),
                    "durSec": 2.4, "scale": 1.55,
                    "focusX": sh.get("clickX", 50), "focusY": sh.get("clickY", 50),
                }]
            if zooms:
                seg["zooms"] = [
                    {"atSec": float(z["atSec"]), "durSec": float(z["durSec"]),
                     "scale": float(z.get("scale", 1.6)),
                     "focusX": float(z.get("focusX", 50)), "focusY": float(z.get("focusY", 50))}
                    for z in zooms
                ]
            if sh.get("sound"):   # UGC talking-head: play the clip's own audio (the creator's voice)
                seg["sound"] = True
        elif kind == "strip":
            seg.update(src=asset(sh["src"]))
        elif kind == "split":
            seg.update(srcL=asset(sh.get("srcL")), inL=sh.get("inL", 0), labelL=sh.get("labelL", ""),
                       srcR=asset(sh.get("srcR")), inR=sh.get("inR", 0), labelR=sh.get("labelR", ""))
        elif kind in ("title", "stat", "bars"):
            seg.update(title=sh.get("title", cap), eyebrow=sh.get("eyebrow", ""),
                       subtitle=sh.get("subtitle", ""), caption="")
            if kind == "bars":
                for k in ("takes", "passLine", "takeLabels", "scoreMax"):
                    if k in sh:
                        seg[k] = sh[k]
        elif kind == "score":
            seg.update(title=sh.get("title", ""), eyebrow=sh.get("eyebrow", ""),
                       score=sh.get("score", 72),
                       scoreMax=sh.get("scoreMax", 100), caption="")
        elif kind == "cta":
            cta = brand.get("cta") if isinstance(brand, dict) else None
            cta = cta if isinstance(cta, dict) else {}
            name = cta.get("name") or (brand.get("name") if isinstance(brand, dict) else None)
            accentw = cta.get("accent") or (brand.get("accent") if isinstance(brand, dict) else None)
            url = cta.get("url") or (brand.get("url", "") if isinstance(brand, dict) else "")
            seg.update(title=sh.get("title", cap), brand=name, brandAccent=accentw,
                       eyebrow=sh.get("eyebrow", ""),
                       subtitle=sh.get("subtitle") or url, caption="")
        segs.append(seg)

    # Per-shot speech may lengthen a segment. Re-run the deterministic contract against those
    # effective durations so audio cannot silently push the final film past its source range or
    # hard runtime after the earlier script-only preflight passed.
    duration_changed = any(
        abs(float(shot.get("durSec", 2.5)) - float(seg["durSec"])) > 0.001
        for shot, seg in zip(script["shots"], segs)
    )
    if args.contracts != "off" and duration_changed:
        effective = json.loads(json.dumps(script))
        for shot, seg in zip(effective["shots"], segs):
            shot["durSec"] = seg["durSec"]
        effective_findings = validate_script(effective, proj, args.profile or None)
        effective_report = summarize(effective_findings)
        for finding in effective_findings:
            where = f" shot {finding.shot}" if finding.shot is not None else ""
            print(f"  EFFECTIVE CONTRACT {finding.severity}: {finding.code}{where} — {finding.message}")
        block_warnings = args.contracts == "strict"
        block_errors = args.contracts != "warn"
        if ((block_errors and effective_report["errors"])
                or (block_warnings and effective_report["warnings"])):
            sys.exit("effective post-VO contract failed: "
                     f"{effective_report['errors']} errors, {effective_report['warnings']} warnings")

    # fail loud: every referenced asset must exist in the staged public/ dir
    missing = []
    for s in segs:
        for k in ("src", "srcL", "srcR"):
            p = s.get(k)
            if p and not os.path.exists(os.path.join(stage_root, p)):
                missing.append(f"shot kind={s['kind']}: {p}")
    if missing:
        sys.exit("missing assets:\n  " + "\n  ".join(missing))

    legacy_mode = args.mode
    if args.mode == "yc" and (args.profile or production.get("profile")):
        print("  LINT warn: --mode yc is the legacy short-demo contract; explicit --profile/production.profile governs instead")
        legacy_mode = "default"
    if legacy_mode == "yc" and music and not args.keep_music:
        music = None   # the YC wrapper is a plain screen recording; polish lives inside the output excerpt

    # Integer frames are the canonical timeline. Root.tsx and Timeline.tsx consume the same
    # per-segment plan, eliminating the 1–2 frame drift caused by rounding total seconds twice.
    plan_segments, total_frames = compile_frame_plan(segs, fps)
    total = total_frames / fps
    if args.contracts != "off":
        frame_effective = json.loads(json.dumps(script))
        for shot, seg in zip(frame_effective["shots"], segs):
            shot["durSec"] = seg["durSec"]
        frame_findings = validate_script(frame_effective, proj, args.profile or None)
        frame_report = summarize(frame_findings)
        for finding in frame_findings:
            where = f" shot {finding.shot}" if finding.shot is not None else ""
            print(f"  FRAME CONTRACT {finding.severity}: {finding.code}{where} — {finding.message}")
        block_warnings = args.contracts == "strict"
        block_errors = args.contracts != "warn"
        if ((block_errors and frame_report["errors"])
                or (block_warnings and frame_report["warnings"])):
            sys.exit("frame-normalized contract failed: "
                     f"{frame_report['errors']} errors, {frame_report['warnings']} warnings")
    errors, warns = lint(script, segs, music, legacy_mode)
    for w in warns:
        print(f"  LINT warn: {w}")
    if errors:
        sys.exit("LINT errors:\n  " + "\n  ".join(errors))

    props = {"fps": fps, "totalSec": total, "totalFrames": total_frames,
             "buildId": build_id, "profile": args.profile or production.get("profile"),
             "music": music, "narration": narration_props,
             "musicVolume": script.get("musicVolume", 0.1),
             "musicFadeOutSec": script.get("musicFadeOutSec", 1.5),
             "sfx": sfx, "theme": theme, "segments": segs}
    props_sha = hashlib.sha256(json.dumps(props, sort_keys=True, separators=(",", ":")).encode()).hexdigest()
    plan = {
        "schemaVersion": 2,
        "buildId": build_id,
        "project": proj,
        "profile": props.get("profile"),
        "script": {"path": script_path, "sha256": sha256_file(script_path)},
        "brand": ({"path": brand_path, "sha256": sha256_file(brand_path)}
                  if os.path.exists(brand_path) else None),
        "assets": source_records,
        "inputs": input_records,
        "buildConfig": build_config,
        "publicDir": stage_root,
        "fps": fps,
        "totalFrames": total_frames,
        "totalSec": total,
        "segments": plan_segments,
        "propsSha256": props_sha,
    }
    project_out = os.path.join(proj, "out")
    os.makedirs(project_out, exist_ok=True)
    write_json(os.path.join(project_out, "props.json"), props)
    write_json(os.path.join(project_out, "build-plan.json"), plan)
    print(f"{len(segs)} segments, {total:.3f}s / {total_frames} frames, build={build_id}, music={'yes' if music else 'none'}")

    if args.dry:
        print("dry run (props written, render skipped)")
        return

    out = args.out or os.path.join(proj, "out", "demo.mp4")
    out = os.path.abspath(out)
    os.makedirs(os.path.dirname(out), exist_ok=True)
    # Keep the plan and props beside the render so every downstream judge/QA can bind to the
    # exact artifact instead of accidentally reviewing a similarly named old file.
    stem, ext = os.path.splitext(os.path.basename(out))
    stem_base = os.path.join(os.path.dirname(out), stem)
    render_props = f"{stem_base}.props.json"
    write_json(render_props, props)
    write_json(os.path.join(os.path.dirname(out), "props.json"), props)  # legacy/default-output convenience
    write_json(f"{stem_base}.build-plan.json", plan)
    write_json(os.path.join(os.path.dirname(out), "build-plan.json"), plan)
    render_tmp = os.path.join(os.path.dirname(out), f".{stem}.{build_id}.rendering{ext or '.mp4'}")
    if os.path.exists(render_tmp):
        os.unlink(render_tmp)
    # The renderer consumes this build's immutable output-adjacent props rather than the shared
    # Studio convenience file in engine/public. Concurrent projects cannot swap timelines.
    cmd = ["npx", "remotion", "render", "Timeline", render_tmp,
           f"--props={render_props}", f"--public-dir={stage_root}",
           "--concurrency=2", "--log=error"]
    print("rendering ->", out)
    r = subprocess.run(cmd, cwd=engine)
    print("render exit:", r.returncode)
    if r.returncode != 0:
        if os.path.exists(render_tmp):
            os.unlink(render_tmp)
        sys.exit(r.returncode)
    probe = subprocess.run(
        ["ffprobe", "-v", "error", "-count_frames", "-select_streams", "v:0",
         "-show_entries", "stream=nb_read_frames,width,height,r_frame_rate:format=duration",
         "-of", "json", render_tmp], capture_output=True, text=True,
    )
    if probe.returncode != 0:
        os.unlink(render_tmp)
        sys.exit("render completed but ffprobe failed; artifact manifest not written")
    observed = json.loads(probe.stdout)
    observed_stream = next(iter(observed.get("streams", [])), {})
    observed_frames = int(observed_stream.get("nb_read_frames") or 0)
    observed_duration = float((observed.get("format") or {}).get("duration") or 0.0)
    if observed_frames != total_frames:
        os.unlink(render_tmp)
        sys.exit(f"render frame mismatch: expected {total_frames}, observed {observed_frames}")
    # Container duration may include AAC encoder padding. The exact picture contract is the integer
    # frame count above; retain the measured container duration for downstream audio QA.
    if abs(observed_duration - total) > max(0.10, 3 / fps):
        os.unlink(render_tmp)
        sys.exit(f"render container duration is implausible: expected about {total:.3f}s, "
                 f"observed {observed_duration:.3f}s")
    os.replace(render_tmp, out)
    artifact = {
        "schemaVersion": 2,
        "buildId": build_id,
        "project": proj,
        "scriptSha256": plan["script"]["sha256"],
        "propsSha256": props_sha,
        "expected": {"fps": fps, "frames": total_frames, "durationSec": total,
                     "width": 1920, "height": 1080},
        "observed": observed,
        "output": {"path": out, "sha256": sha256_file(out),
                   "bytes": os.path.getsize(out)},
        "assets": source_records,
        "inputs": input_records,
    }
    stem_artifact = f"{stem_base}.artifact.json"
    write_json(stem_artifact, artifact)
    write_json(os.path.join(os.path.dirname(out), "artifact.json"), artifact)  # backward compatible
    print(f"artifact -> {stem_artifact}")


if __name__ == "__main__":
    main()
